from supabase import create_client

SUPABASE_URL = "https://fhumorwedybuhkpbvxzm.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZodW1vcndlZHlidWhrcGJ2eHptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUzNDU3NzYsImV4cCI6MjA5MDkyMTc3Nn0.-_IRubVlr0XysRJt2yADymDIpCP74IsQOCiZNzizMtk"

supabase = create_client(SUPABASE_URL, SUPABASE_KEY)
